### ISSUE TITLE
ES6 or Coffee

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-device-sdk#3]
If we write this project from scratch. What do you think is better? Coffee or ES6?

**Comment by kosssi** [comment]
:+1: for ES6

But coffee is the cozy stack?

**Comment by frankrousseau** [comment]
I remember that we said in TC that Coffee is closed to deprecation. So we should not use it for new projects. @nono @m4dz @aenario any memories about it?

**Comment by nono** [comment]
I remember it was said in a TC, but I didn't find anything written. It was probably before @kosssi joins CozyCloud.

**Comment by m4dz** [comment]
Same as @nono: I think it was before we take minutes on TC.

It seems legit, as long as we took the choice of ES6 for _Konnectors_ and the upcoming _Cozic_ apps. ES6 is the now to use futur, and the bundlers take care of mixed codebased for us. So I :+1: ES6 for new projects too :smile: (plus, It'll bring us more kownledges about it, which will help when we decided to port existing apps later)

**Comment by frankrousseau** [comment]
Coffeescript still looks maintained and its trend stopped falling down. But people are crazy about ES6. So let's go for it.
